# Identificación del proyecto
sonar.projectKey=ecomove-frontend # -> Misma key que se establece en Sonnar
sonar.projectName=EcoMove Frontend # -> Mismo nombre que se establece en Sonnar
sonar.projectVersion=0.4 # -> Version con la que vamos a trabajar

sonar.sources=src # -> Directorios a analizar

sonar.exclusions=**/node_modules/**,**/dist/**,**/*.config.ts,**/*.config.js,**/vite-env.d.ts,**/*.svg # -> Lo que NO vamos a analizar

sonar.typescript.tsconfigPath=tsconfig.json # ->  Le indicamos a SonarQube dónde está el archivo de configuración de TypeScript

sonar.language=ts,tsx,js,jsx # -> Definimos qué lenguajes debe analizar SonarQube

sonar.sourceEncoding=UTF-8 # -> Indica la codificación de caracteres de los archivos fuente

# Para el uso de tests (NO obligatorio)
# sonar.tests=src
# sonar.test.inclusions=**/*.test.tsx,**/*.test.ts,**/*.spec.tsx,**/*.spec.ts

# Cobertura de código (en caso de tests)
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
# sonar.typescript.lcov.reportPaths=coverage/lcov.info