trigger:
    - main ## -> en que rama se ejecuta el pipeline
    - Develop
pool:
    name: agent-test ## -> nombre del pool agente donde se ejecuta el pipeline

variables:
  backendVersion: '0.0.2'

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob
        displayName: 'Build Job'
        steps:
          - task: Docker@2
            displayName: 'Docker'
            inputs:
              containerRegistry: 'DockerTest'
              repository: 'jdavidperalta/backend-pipeline'
              command: 'build'
              Dockerfile: 'Backend/Dockerfile'
              buildContext: 'Backend'
              arguments: '--build-arg ENVIRONMENT=$(Build.SourceBranchName)'
              tags: |
                $(backendVersion)
          - task: Docker@2
            displayName: 'Push Image'
            inputs:
              containerRegistry: 'DockerTest'
              repository: 'jdavidperalta/backend-pipeline'
              command: 'push'
              tags: |
                $(backendVersion)
          - task: Bash@3
            displayName: 'Display Image Info'
            inputs:
              targetType: 'inline'
              script: |
                docker stop testupc || true
                docker rm testupc || true
                docker run -d --name testupc -p 3000:3000 jdavidperalta/backend-pipeline:$(backendVersion)
                docker rm testupc || true
                docker image prune -f