sonar.projectKey=ecomove-backend # -> Misma key que se establece en Sonnar
sonar.projectName=EcoMove Backend # -> Mismo nombre que se establece en Sonnar
sonar.projectVersion=0.0.2 # -> Version con la que vamos a trabajar

sonar.sources=src # -> Directorios a analizar

sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/coverage/**,**/*.spec.ts,**/*.test.ts,**/drizzle/**,**/UMls/** # -> Lo que NO vamos a analizar

sonar.typescript.tsconfigPath=tsconfig.json # ->  Le indicamos a SonarQube dónde está el archivo de configuración de TypeScript

sonar.language=ts # -> Definimos qué lenguajes debe analizar SonarQube

sonar.sourceEncoding=UTF-8 # -> Indica la codificación de caracteres de los archivos fuente


# sonar.typescript.lcov.reportPaths=coverage/lcov.info