export enum StatusVehicle {
  AVAILABLE = 'AVAILABLE',
  IN_USE = 'IN_USE',
  OUT_OF_SERVICE = 'OUT-OF-SERVICE',
  MAINTENANCE = 'MAINTENANCE',
}

export enum VehicleType {
  BICYCLE = 'BICYCLE',
  ELECTRIC_SCOOTER = 'ELECTRIC_SCOOTER',
  SKATEBOARD = 'SKATEBOARD',
  CAR_ELECTRIC = 'CAR_ELECTRIC'
}
