export { default as BicycleFields } from "./bicycle"
export { default as ElectricBicycleFields } from "./electricBicycle"
export { default as ScooterFields } from "./scooter"
export { default as ElectricScooterFields } from "./electricScooter"
export { default as CarElectricFields } from "./carElectric"
export { default as SkateboardFields } from "./skateboard"
export { default as ElectricSkateboardFields } from "./electricSkateboard"